version: '3.0'


services:
  db:
    image: postgres
    container_name: sight-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  redis:
    image: redis
    container_name: sight-redis
    ports:
      - "6379:6379"
    restart: on-failure

  web:
    build: .
    command: bash -c "pip install --upgrade pip && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/sight
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true



volumes:
  postgres_data:
