# Generated by Django 5.0.3 on 2024-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobileoperatorcode",
            name="operator_code",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
