# Generated by Django 5.0.3 on 2024-03-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_alter_client_options_alter_client_client_timezone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
    ]
