# Generated by Django 5.0.3 on 2024-03-13 19:13

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_alter_client_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=12, region="RU", unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
