# Generated by Django 5.0.3 on 2024-03-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0007_mobileoperatorcode_mailing_tag_mailing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobileoperatorcode",
            name="mailing",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="mailing",
        ),
    ]
