# Generated by Django 5.0.3 on 2024-03-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0008_remove_mobileoperatorcode_mailing_remove_tag_mailing"),
        ("message", "0003_remove_message_client_alter_message_mailing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="client",
        ),
        migrations.AddField(
            model_name="message",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.client",
                verbose_name="Клиент",
            ),
        ),
    ]
