# Generated by Django 5.0.3 on 2024-03-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime_mailing",
                    models.DateTimeField(verbose_name="Начало запуска рассылки"),
                ),
                (
                    "end_datetime_mailing",
                    models.DateTimeField(verbose_name="Окончание рассылки"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
            ],
        ),
    ]
