# Generated by Django 5.0.3 on 2024-03-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AddField(
            model_name="mailing",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
