# Generated by Django 5.0.3 on 2024-03-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_options_mailing_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="title",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Тема сообщения"
            ),
        ),
    ]
