# Generated by Django 5.0.3 on 2024-03-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_mailing_mobile_operator_code_mailing_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="mobile_operator_code",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="tag",
        ),
        migrations.CreateModel(
            name="MailingMixin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
        ),
    ]
