# Generated by Django 5.0.3 on 2024-03-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_remove_mailing_mobile_operator_code_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MailingMixin",
        ),
    ]
