# Generated by Django 5.0.3 on 2024-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0008_remove_mobileoperatorcode_mailing_remove_tag_mailing"),
        ("mailing", "0008_remove_mailing_mobile_operator_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="mobile_operator_code",
            field=models.ManyToManyField(
                to="client.mobileoperatorcode", verbose_name="Мобильный код оператора"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="tag",
            field=models.ManyToManyField(to="client.tag", verbose_name="Тэг"),
        ),
    ]
